.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "PARFAIT" "1" "February 2021" "" ""
.
.SH "NAME"
\fBparfait\fR \- Java instrumentation for Performance Co\-Pilot (PCP)
.
.SH "SYNOPSIS"
\fBparfait\fR [\fB\-n\fR \fIname\fR] [\fB\-c\fR \fIid\fR] [\fB\-i\fR \fImsec\fR] [\fB\-s\fR \fIdelay\fR] [[\fB\-\-jmxserver\fR] | [\fB\-\-connect\fR \fIhost:port\fR]] [\fB\-\-\fR] [\fBjavaargs\fR \.\.\.]
.
.SH "DESCRIPTION"
The \fBparfait\fR wrapper script provides instrumentation for an \fIunmodified\fR Java application\. It is a front end to the Parfait \fIhttps://github\.com/performancecopilot/parfait\fR modules which developers use to access instrumentation from Java applications\.
.
.P
The \fBparfait\fR script is limited to exposing performance metrics that it can find indirectly, such as via JMX\.
.
.P
In order to be exported to the PCP Memory Mapped Values PMDA (see \fBpmdammv\fR(1) for details) these metrics must first be categorized with PCP metadata\.
.
.P
This is performed by configuration of the \fIparfait\-agent\.jar\fR file used by \fBparfait\fR\. In the simplest form the configuration is sourced from files in the \fI/etc/parfait\fR directory\. Additional JMX managed beans can be added to the default set through configuration files in the \fI/etc/parfait\fR directory\.
.
.P
If this directory is empty, does not exist, or is otherwise inaccessible, a minimal configuration is read from within the resources of the \fIparfait\-agent\.jar\fR file\.
.
.P
The available managed beans from a running \fBjava\fR(1) application can be explored using standard Java tools like \fBjconsole\fR(1), when JMX access has been setup as in the EXAMPLES section below\.
.
.P
Configuration files must be in the JSON format \- refer to the CONFIGURATION section below for details of the file format\.
.
.P
There are two forms of instrumentation available from the \fBparfait\fR script \- direct instrumentation (agent mode) or via a JMX server (proxy mode)\.
.
.P
See the EXAMPLES section below for a sample invocation for both modes\.
.
.SH "OPTIONS"
The command line options available are:
.
.TP
\fB\-n\fR \fIname\fR, \fB\-\-name\fR \fIname\fR
The \fIname\fR argument specifies the \fImmv\.*\fR metric tree name in the \fBPMNS\fR(5) that will be used to identify this application\.
.
.TP
\fB\-c\fR \fIidentifier\fR, \fB\-\-cluster\fR \fIidentifier\fR
The numeric performance metric cluster \fIidentifier\fR to be used to uniquely identify this application\. A value of zero is the default, and causes the MMV PMDA to simply use the next available number\.
.
.TP
\fB\-i\fR \fImsec\fR, \fB\-\-interval\fR \fImsec\fR
Delay between sampling (JMX values in particular) to refresh the values exported to PCP, in milliseconds\. The default value is 1000 (1 second) and the minimum allowed value is 250 milliseconds\.
.
.TP
\fB\-j\fR, \fB\-\-jmxserver\fR, \fB\-\-connect\fR \fIhostname:port\fR
Connect to the JMX server listening on the specified \fIhostname\fR and \fIport\fR number as the source of JMX metrics\. This option allows proxying of metrics from a separate process, instead of the default \fB\-javaagent\fR mode of operation\.
.
.TP
\fB\-s\fR / \fB\-\-startup\fR \fImsec\fR
Maximum startup time in which JMX values are still being created, before exporting as memory mapped values, in milliseconds\. The default value is 5000 (5 seconds)\.
.
.TP
\fB\-h\fR / \fB\-\-help\fR
Show a brief usage message and exit\.
.
.SH "EXAMPLES"
The following examples can be installed locally using the \fBparfait\-examples\fR package\.
.
.P
The affects of each example invocation below can be seen using any PCP client tool, such as
.
.IP "\(bu" 4
pminfo \fB\-f\fR mmv
.
.IP "\(bu" 4
pmprobe \fB\-v\fR mmv
.
.IP "\(bu" 4
pmchart
.
.IP "\(bu" 4
pmrep
.
.IP "\(bu" 4
pmie
.
.IP "\(bu" 4
[\.\.\. and many others \.\.\.]
.
.IP "" 0
.
.P
The default mode of operation involves directly running the Java process to be instrumented with a javaagent:
.
.IP "\(bu" 4
\fIparfait\fR \-\-name sleep \-\- \-jar /usr/share/java/parfait/sleep\.jar
.
.IP "" 0
.
.P
Behind the scenes this runs:
.
.IP "\(bu" 4
\fIjava\fR \-Dparfait\.name=sleep \fB\-javaagent\fR:/usr/share/java/parfait/parfait\.jar \-jar /usr/share/java/parfait/sleep\.jar
.
.IP "" 0
.
.P
The alternative is the proxy mode, where an already running Java process is instrumented using its JMX server\. To start the Java application with a JMX server exposed, use the following options:
.
.IP "\(bu" 4
\fIjava\fR \fB\-Dcom\.sun\.management\.jmxremote \-Dcom\.sun\.management\.jmxremote\.port=9875\fR \-Dcom\.sun\.management\.jmxremote\.local\.only=true \-Dcom\.sun\.management\.jmxremote\.authenticate=false \-Dcom\.sun\.management\.jmxremote\.ssl=false \-jar /usr/share/java/parfait/sleep\.jar
.
.IP "" 0
.
.P
The JMX server is then allowing access from instrumentation by \fBparfait\fR, which can be invoked as follows:
.
.IP "\(bu" 4
\fIparfait\fR \-\-name sleep \-\-connect localhost:9875
.
.IP "" 0
.
.P
Behind the scenes this runs:
.
.IP "\(bu" 4
\fIjava\fR \-Dparfait\.name=sleep \-jar /usr/share/java/parfait/parfait\.jar \fB\-connect=localhost:9875\fR
.
.IP "" 0
.
.SH "CONFIGURATION"
The statically configured metrics used by \fBparfait\-agent\fR are configured using JSON configuration files\. The default used when no files are present below \fI/etc/parfait\fR is:
.
.IP "\(bu" 4
\fIjvm\.json\fR \fIhttps://github\.com/performancecopilot/parfait/tree/main/parfait\-agent/src/main/resources/jvm\.json\fR
.
.IP "" 0
.
.P
This provides a handy reference for the semantic elements of the JSON configuration, which are:
.
.TP
The \fBmetrics\fR array
JSON array of individual metrics, must appear at the top level\.
.
.TP
Metric \fBname\fR
A string which forms the dotted\-form metric name, as well as the optional PCP instance name in square brackets\.
.
.TP
Metric \fBdescription\fR
An optional string providing explanatory help text for a metric\.
.
.TP
Metric \fBsemantics\fR
An optional string with one of the following values: \fIconstant\fR or \fIdiscrete\fR; \fIcount\fR or \fIcounter\fR; and \fIgauge\fR, \fIinstant\fR or \fIinstantaneous\fR\. These map directly to the PCP metric semantics\. The value \fIinstantaneous\fR is the default\.
.
.TP
Metric \fBunits\fR
A string which will be parsed to produce the JSR\-363 units for the metric\. Acceptable unit strings include: \fIs\fR, \fIseconds\fR, \fIms\fR, \fImilliseconds\fR, \fIµs\fR, \fImicroseconds\fR, \fIns\fR, \fInanoseconds\fR, \fIB\fR, \fIbyte\fR, \fIbytes\fR, \fIKiB\fR, \fIKbyte\fR, \fIMiB\fR, \fIMbyte\fR, \fIGiB\fR, \fIGbyte\fR, \fITiB\fR, \fITbyte\fR, \fIEiB\fR, \fIEbyte\fR, as well as \fInone\fR, \fIone\fR and the empty string\.
.
.TP
Whether the metric is \fBoptional\fR
A boolean (default: \fIfalse\fR) which flags whether this metric must exist in the JVM\. Certain metrics only appear in some situations, or some versions of the JVM, these should be marked as \fBoptional\fR metrics\.
.
.TP
Managed bean name \fBmBeanName\fR
A string used to identify the Java managed bean backing this metric in the JVM (e\.g\. \fIjava\.lang:type=Memory\fR)\.
.
.TP
Managed bean attribute name \fBmBeanAttributeName\fR
An optional string used to identify a specific attribute of a managed bean (e\.g\. \fIHeapMemoryUsage\fR)\.
.
.TP
Managed bean composite data item (\fBmBeanCompositeDataItem\fR)
An optional string used to further classify an individual value of the managed bean attribute (e\.g\. \fImax\fR)\.
.
.SH "ENVIRONMENT"
The contents of the environment variable \fBPARFAIT_JAVA_OPTS\fR, if any, are inserted into the java command line before the \fI\-javaagent\fR argument and before any arguments in \fIjavaargs\fR\.
.
.SH "FILES"
.
.TP
\fI$PCP_TMP_DIR/mmv/*\fR
memory mapped values files created by \fBparfait\fR\.
.
.TP
\fI/etc/parfait/*\.json\fR
configuration files defining metrics in the format described above\.
.
.SH "LINKS"
Parfait \fIhttps://github\.com/performancecopilot/parfait\fR:
.
.IP "\(bu" 4
Default metrics \fIhttps://github\.com/performancecopilot/parfait/tree/main/parfait\-agent/src/main/resources/jvm\.json\fR
.
.IP "" 0
.
.P
Performance Co\-Pilot \fIhttp://pcp\.io\fR:
.
.IP "\(bu" 4
\fBPCPIntro\fR \fIhttp://man7\.org/linux/man\-pages/man1/pcpintro\.1\.html\fR
.
.IP "\(bu" 4
\fBpmcd\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmcd\.1\.html\fR
.
.IP "\(bu" 4
\fBpmchart\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmchart\.1\.html\fR
.
.IP "\(bu" 4
\fBpmdammv\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmdammv\.1\.html\fR
.
.IP "\(bu" 4
\fBpmie\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmie\.1\.html\fR
.
.IP "\(bu" 4
\fBpminfo\fR \fIhttp://man7\.org/linux/man\-pages/man1/pminfo\.1\.html\fR
.
.IP "\(bu" 4
\fBpmprobe\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmprobe\.1\.html\fR
.
.IP "\(bu" 4
\fBpmrep\fR \fIhttp://man7\.org/linux/man\-pages/man1/pmrep\.1\.html\fR
.
.IP "\(bu" 4
\fBPMAPI\fR \fIhttp://man7\.org/linux/man\-pages/man3/PMAPI\.3\.html\fR
.
.IP "\(bu" 4
\fBPMNS\fR \fIhttp://man7\.org/linux/man\-pages/man5/pmns\.5\.html\fR
.
.IP "" 0
.
.SH "SEE ALSO"
\fBjava\fR(1), \fBjconsole\fR(1), \fBPCPIntro\fR(1), \fBpmcd\fR(1), \fBpmchart\fR(1) \fBpmdammv\fR(1) \fBpmie\fR(1), \fBpminfo\fR(1), \fBpmprobe\fR(1), \fBpmrep\fR(1), \fBPMAPI\fR(3), and \fBPMNS\fR(5)\.
