name: ci

on: [ push, pull_request ]

jobs:
  java:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        java-version: ['11', '17', '21']
    steps:
      - uses: actions/checkout@v4
      - name: install pcp
        run: |
          curl -s https://packagecloud.io/install/repositories/performancecopilot/pcp/script.deb.sh | sudo bash
          sudo apt-get update -q
          sudo apt-get install -y pcp pcp-zeroconf
      - name: verify pcp install
        run: pcp
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java-version }}
      - name: check mmv permissions
        run: ls -la /var/lib/pcp/tmp/ | grep mmv
      - name: open up access
        run: sudo chmod o+w /var/lib/pcp/tmp/mmv
      - name: verify parfait
        run: mvn -B -V clean install verify
