name: ci

on: [ push, pull_request ]

jobs:
  java:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: install pcp
        run: |
          curl -s https://packagecloud.io/install/repositories/performancecopilot/pcp/script.deb.sh | sudo bash
          sudo apt-get update -q
          sudo apt-get install -y pcp-zeroconf
      - name: verify pcp install
        run: pcp
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: open up access
        run: sudo chmod o+w /var/lib/pcp/tmp/mmv
      - name: verify parfait
        run: mvn -B -V clean install verify
